name: NeonSpawn
main: com.neonstudios.neonspawn.NeonSpawn
version: 1.4
api-version: 1.13
commands:
  spawn:
    description: Teleport to spawn
  setspawn:
    description: Set the spawn location
    permission: neonspawn.setspawn
  neonspawn:
    description: Main plugin management command
    usage: /<command> reload
    permission: neonspawn.reload
    permission-message: "&cYou don't have permission to use this command."
permissions:
  neonspawn.setspawn:
    description: Allows setting the spawn point
    default: op
  neonspawn.reload:
    description: Allows reloading NeonSpawn config and messages
    default: op