# NeonSpawn
# Developed by NeonStudios
# Discord: https://dsc.gg/neonstudios

# Version 0.1.5
# Configuration for NeonSpawn plugin
# This file is used to configure the spawn settings and effects for the NeonSpawn plugin.

teleport-delay: 5 # Seconds before teleport

first-join:
  message-type: "chat" # or "title"
  sound: "ENTITY_PLAYER_LEVELUP"
  particle: "HAPPY_VILLAGER"
  particle-amount: 40
  particle-offset: 0.5
  sound-volume: 1.2
  sound-pitch: 1.0


spawn:
  world: world
  x: 0
  y: 64
  z: 0
  yaw: 0
  pitch: 0

cancel-on-move: true
cancel-on-block-change-only: true # Only cancels if player moves to a different block (not just head movement)

enable-actionbar: true
enable-bossbar: true
enable-title: true
enable-particles: true
enable-sounds: true

effects:
  actionbar:
    teleport-start: true
    teleport-cancelled: true
    teleport-success: true

  bossbar:
    teleport-start: true
    teleport-cancelled: true
    teleport-success: true

  title:
    teleport-success:
      fadeIn: 10
      stay: 40
      fadeOut: 10

  particles:
    teleport-start: "VILLAGER_HAPPY"
    teleport-cancelled: "SMOKE_LARGE"
    teleport-success: "END_ROD"

  sounds:
    teleport-start: "BLOCK_NOTE_BLOCK_PLING"
    teleport-cancelled: "ENTITY_ITEM_BREAK"
    teleport-success: "ENTITY_PLAYER_LEVELUP"
