name: NeonSpawn
main: com.neonstudios.neonspawn.NeonSpawn
version: 1.0
api-version: 1.13
commands:
  spawn:
    description: Teleport to spawn
  setspawn:
    description: Set the spawn location
    permission: neonspawn.setspawn
  spawnmenu:
    description: Open the spawn GUI
permissions:
  neonspawn.setspawn:
    description: Allows setting the spawn point
    default: op
